### PR TITLE
Carthage support

### PR DESCRIPTION
**Pull request by sauravexodus**

### CODE REVIEW

**Comment by freak4pc** [comment]
Hey there - I suggest looking into the many issues on Carthage in the repo. 
Basically this project is maintained by the community but owned by @devxoul who has decided against using an Xcodeproj (since he uses SPM, and a separate project just for supporting Carthage was something he is against).

Basically, I don't think this sort of PR will be merged, but I will leave this to the decision of the project owner when he has the time to look at it.

**Comment by devxoul** [comment]
There is a goods news: https://github.com/Carthage/Carthage/pull/1945#issuecomment-459768650 I think we can wait for this :tada:

**Comment by freak4pc** [comment]
It would only solve the issue for Swift 5 and up, but it's still great news :) Swift 5 is going to solve a lot of issues for package maintainers.

**Comment by sauravexodus** [comment]
Sounds good!

**Comment by mendesbarreto** [comment]
Hey @devxoul maybe now this is a dead-end?  

https://github.com/Carthage/Carthage/pull/1945#issuecomment-510121766

**Pull request closed without merging**
