### PR TITLE
Add isPanAvailable

### PR DESCRIPTION
**Pull request by anukhov**

### CODE REVIEW

**Comment by devxoul** [comment]
@anukhov, thanks for you work. Could you please provide me some detailed explanation for this feature?

**Comment by anukhov** [comment]
@devxoul sometimes there is no need to observe detailed tracking of keyboard frame, but it is convenient to use a one Pod

**Comment by devxoul** [comment]
@anukhov, Thanks. Could you please change the 4-space-indentation to 2-space?

**Comment by anukhov** [comment]
@devxoul ok, i changed it. pls, see my commits

**Comment by devxoul** [comment]
@anukhov, Can you please re-organize unnecessary commits by `rebase -i HEAD~5`? I think refactoring stuff is not related to this PR.

I think

```diff
+  public var isPanAvailable = true {
+    didSet {
+      panRecognizer.delegate = isPanAvailable ? self : nil
+    }
+  }
```

and

```diff
+    .skipWhile { $0.delegate == nil }
```

is enough with this PR

**Comment by anukhov** [comment]
I think it's not quite the same thing, but I'll try to use it in more detail

**Comment by devxoul** [comment]
@anukhov, Your PR looks good but I'm not really sure when do we need this feature. Couldn't we just set `UIScrollView.keyboardDismissMode` to another?

**Comment by anukhov** [comment]
i need to use tableView.scrollToRow(at: ..., at: .middle ...) when keyboard position is changed. It appears rattling table.

**Comment by devxoul** [comment]
@anukhov You can use `willShowVisibleHeight`. https://github.com/RxSwiftCommunity/RxKeyboard#tip-content-offset

**Comment by anukhov** [comment]
You are right. However i will need to observe visibleheight too , to change tableview insets (when keyboard hides or asebility frame changes). But, ok

**Comment by devxoul** [comment]
You can refer to demo project: https://github.com/RxSwiftCommunity/RxKeyboard/blob/3d6276724bcc3d4a4f841e347c87fd75d57db5b1/Demo/Sources/ViewControllers/MessageListViewController.swift#L92-L111

**Comment by anukhov** [comment]
if you open keyboard then change view controller and start observe willShowVisibleHeight - first emit - will return not zero value

**Comment by devxoul** [comment]
@anukhov, could you please add some details? I think you could use `self.view.endEditing(true)` on your view controller before pushing/presenting a new view controller. This can prevent some UI issues on general iOS projects.

**Comment by anukhov** [comment]
I think we can close PR. I have create extension for rxkeyboard and incapsulate all i need there. It's better for me , so i can use it easy in other projects.
And what about willshowvisibleheight - I think endediting can't help us. I combine visibleheight and willshowvisibleheight with skip first. I think skip first for willshowvisibleheight is more clear for this.

**Pull request closed without merging**
