### PR TITLE
rxKeyboard: use private access modifier when needed

### PR DESCRIPTION
**Pull request by r-mckay**
Hi!

This commit replaces the `fileprivate` access modifiers by `private`
when it is needed.

Thanks!

### CODE REVIEW

**Comment by r-mckay** [comment]
Thank you!

**Comment by Incorporalis** [comment]
Hey guys! Now it looks as build failing error. 

Xcode 9.3 and swift 3.3
Could you please revert accessibility modifier for `panRecognizer`, it is used in extension, so it is inaccessible.

Thank you in advance.

**Comment by freak4pc** [comment]
Hey @Incorporalis. I'm not the maintainer of RxKeyboard, but generally we don't support Swift 3 at all on the latest versions. Feel free to target a previous release.

**Comment by Incorporalis** [comment]
Okay, I got it. Thanks :)

**Pull request merged**
