### PR TITLE
Fixed protection level of pan recognizer

### PR DESCRIPTION
**Pull request by stevejcox**
Resolves Xcode 9.4.1 / Swift 4.1 protection level compile error.

### CODE REVIEW

**Comment by freak4pc** [comment]
Hey @stevejcox, thanks for your contribution! 

Why would you need direct access to the gesture recognizer? the entire premise of the keyboard is to reactively wrap the keyboard.

**Comment by stevejcox** [comment]
I'm with you with that, however for some reason when compiling with XCode 9.4.1 Swift 4.1 the extension method `shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer)` line 159 of RxKeyboard.swift throws a protection level error.

Seeing this on both local and CI builds.

**Comment by freak4pc** [comment]
Hey @stevejcox - I'm not getting the issue you do with Swift 4.1 and Xcode 9.4.1. 

Could you confirm locally by using `swift --version` and `swift build` that the version is what you expect, and that you're seeing the build issue in the CLI as well?

**Comment by stevejcox** [comment]
It's weird, I don't know why it would have an issue with that protection level since it's just accessing in the extension. That being said, I do get it on both main workstation and CLI.

Workstation Swift results below:
`
Apple Swift version 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
`

Perhaps it's one of those funny XCode compiler issues.

**Comment by freak4pc** [comment]
Can you paste your entire build.log here and make sure you “git pull”d the latest commits from master ?

**Comment by devxoul** [comment]
How did you install RxKeyboard? (e.g. CocoaPods or Carthage)

**Comment by stevejcox** [comment]
Sorry guys, not been at my machine with this to be able to send you the build log. Installed via CocoaPods. I'll get the build log to you when I get chance.

**Pull request closed without merging**
