### PR TITLE
Let's Swift 5.0 🚀

### PR DESCRIPTION
**Pull request by devxoul**
Nothing has really changed 🤔

### CODE REVIEW

**Comment by freak4pc** [comment]
@devxoul Do you want to release this?

**Comment by devxoul** [comment]
@freak4pc Oh I was waiting for the Travis CI and totally forgot this 🤭 I think it is good timing!

**Comment by devxoul** [comment]
@freak4pc Do you think we should bump the RxSwift dependency version to [4.5.0](https://github.com/ReactiveX/RxSwift/releases/tag/4.5.0) for Swift 5?

**Comment by freak4pc** [comment]
@freak4pc Yup, definitely. Especially because of carthage.

**Pull request merged**
