### PR TITLE
Variable replacing to BehaviorRelay

### PR DESCRIPTION
**Pull request by Tawfikk**
`Variable` is planned for future deprecation.

### CODE REVIEW

**Comment by Tawfikk** [comment]
perfectly .....

**Comment by devxoul** [comment]
I think we should use `BehaviorSubject` instead.

**Comment by devxoul** [comment]
We need another change:

```diff
 Observable.of(didPan, willChangeFrame, willHide).merge()
-  .bind(to: frameVariable)
+  .subscribe(onNext: { [weak frameVariable] frame in
+    frameVariable?.accept(frame)
+  })
   .disposed(by: self.disposeBag)
```

**Comment by freak4pc** [comment]
@devxoul Why BehaviorSubject in this case? I think it can't error.

**Comment by devxoul** [comment]
@freak4pc I was confused :) I edited my comment right after I post it.

**Comment by freak4pc** [comment]
@devxoul I'll delete mine :)

**Comment by freak4pc** [comment]
Looks good, Just want to confirm @devxoul 
Why did you request a change away from `bind(to: Relay)` ? That should work on RxSwift 4.1 and up, unless you don't want to depend on that version.

**Comment by devxoul** [comment]
@freak4pc I didn't know that binding method exists in 4.1. I was using 4.0 😱 I think we can easily bump the RxSwift dependency to 4.1 later so I'm going to merge this first :)

**Comment by freak4pc** [comment]
Welcome to RxSwiftCommunity @Tawfikk ! Thanks for your contribution :)

**Comment by Tawfikk** [comment]
@freak4pc thanks for the invite)))

**Pull request merged**
