### PR TITLE
Make compatible with RxSwift 4.4.0 and Xcode 10.1

### PR DESCRIPTION
**Pull request by RafaelPlantard**

### CODE REVIEW

**Comment by RafaelPlantard** [comment]
Can anyone review it? @RxSwiftCommunity/contributors

**Comment by freak4pc** [comment]
I'm a bit confused - If someone is using RxSwift 4.4.0, they would have no problem using this. There isn't really a compatibility issue that I see. Did you experience any issue here?

**Comment by RafaelPlantard** [comment]
@freak4pc my real problem is that I'm using Carthage and the latest version of RxKeyboard was compiled with Swift 4.1.2, and Xcode 10.1 version of swift is 4.2

**Comment by RafaelPlantard** [comment]
For while I forked this project and using deploy code on travis.yml, I generate a new zip artefact

**Comment by AlexisQapa** [comment]
Can this be merged and a new binary built so we can use Carthage the easy way ?

**Comment by freak4pc** [comment]
I think this is solved in #81

**Pull request closed without merging**
