### PR TITLE
Adding Carthage support for binary-only distribution

### PR DESCRIPTION
**Pull request by bsarrazin**
As discussed in #47 
Here's the fix, along with updated documentation.

### CODE REVIEW

**Comment by freak4pc** [comment]
PS can't we support both syntaxes?

**Comment by bsarrazin** [comment]
@freak4pc if we say that we support `github "RxSwiftCommunity/RxKeyboard"` then we'd need to actually support it by adding an Xcode project in this repo. If you see the discussion in #45 there is little interest from @devxoul to truly support Carthage in this fashion.

**Comment by freak4pc** [comment]
Oh right :) forgot the context. LGTM as soon as this is green and @devxoul has a second to look at this

**Comment by devxoul** [comment]
I really love this. Thanks for your contribution :tada:

**Pull request merged**
