### PR TITLE
Remove Carthage (CocoaPods is already being used with more dependencies)

### PR DESCRIPTION
**Pull request by carlosypunto**

### CODE REVIEW

**Comment by tonyarnold** [comment]
Why would you not want Carthage support?

Also, you appear to have pulled in many unrelated changes in this PR.

**Comment by carlosypunto** [comment]
Carthage support still exist, look the code please

**Comment by carlosypunto** [comment]
You can check Carthage still supported here: https://dl.dropboxusercontent.com/u/2878917/RxKeyboardCarthageSupportTest.zip

**Comment by carlosypunto** [comment]
I close it to favor of #8

**Pull request closed without merging**
